#Server Configuration
spring.application.name=BackendApi
server.servlet.context-path=/api
#Security Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/minedesso
#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/minedesso
spring.datasource.username=postgres
spring.datasource.password=*Excelon1
spring.liquibase.change-log=classpath:/db/db.changelog-master.xml