#Server Configuration
spring.application.name=BackendApi
server.servlet.context-path=/api
#Swagger-UI Configuration
springdoc.swagger-ui.oauth.client-id=swagger-ui
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth2-redirect-url=http://localhost:8080/api/swagger-ui/oauth2-redirect.html
springdoc.swagger-ui.persistAuthorization=true
#Security Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/minedesso
#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/minedesso
spring.datasource.username=postgres
spring.datasource.password=*Excelon1
spring.liquibase.change-log=classpath:/db/db.changelog-master.xml